# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: mmozeiko/mingw-w64

build:
  stage: build
  before_script:
     - apt update && apt -y install make autoconf
  script:
    - make searcher
    - make server
    - x86_64-w64-mingw32-gcc -o server.exe layers.c generator.c finders.c util.c server.c
    - x86_64-w64-mingw32-gcc -o searcher.exe layers.c generator.c finders.c util.c searcher.c
  artifacts:
    paths:
      - searcher
      - searcher.exe
      - server
      - server.exe
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - ./runmytests.sh
